class GetIterativeChallengeInstance {
  final String itemId;
  final String name;
  final String type;
  final int coinAmount;
  final String price;
  final String description;
  final String locale;
  final String category;

  const GetIterativeChallengeInstance({
    required this.itemId,
    required this.name,
    required this.type,
    required this.coinAmount,
    required this.price,
    required this.description,
    required this.locale,
    required this.category,
  });
}

const List<GetIterativeChallengeInstance> shopInventory = <GetIterativeChallengeInstance>[
  GetIterativeChallengeInstance(
    itemId: 'xiangban_1',
    name: '5金币',
    type: 'basic',
    coinAmount: 5,
    price: '¥5',
    description: '5金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_2',
    name: '10金币',
    type: 'basic',
    coinAmount: 10,
    price: '¥10',
    description: '10金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_3',
    name: '15金币',
    type: 'basic',
    coinAmount: 15,
    price: '¥15',
    description: '15金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_4',
    name: '18金币',
    type: 'basic',
    coinAmount: 18,
    price: '¥16',
    description: '18金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_5',
    name: '25金币',
    type: 'basic',
    coinAmount: 25,
    price: '¥20',
    description: '25金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_6',
    name: '50金币',
    type: 'basic',
    coinAmount: 50,
    price: '¥38',
    description: '50金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_7',
    name: '70金币',
    type: 'basic',
    coinAmount: 70,
    price: '¥50',
    description: '70金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_8',
    name: '100金币',
    type: 'basic',
    coinAmount: 100,
    price: '¥68',
    description: '100金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_9',
    name: '200金币',
    type: 'basic',
    coinAmount: 200,
    price: '¥99',
    description: '200金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_10',
    name: '250金币',
    type: 'basic',
    coinAmount: 250,
    price: '¥128',
    description: '250金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_11',
    name: '300金币',
    type: 'basic',
    coinAmount: 300,
    price: '¥138',
    description: '300金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_12',
    name: '400金币',
    type: 'basic',
    coinAmount: 400,
    price: '¥199',
    description: '400金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
  GetIterativeChallengeInstance(
    itemId: 'xiangban_13',
    name: '500金币',
    type: 'basic',
    coinAmount: 500,
    price: '¥249',
    description: '500金币',
    locale: 'zh_CN',
    category: 'basic',
  ),
];
